[package]
name = "example"
version = "0.1.0"
edition = "2024"

[dependencies]
snapshot = { path = "../" }
sdl3 = { version = "0.16.2", features = ["build-from-source"] }
rand = "0.9.2"
rand_distr = "0.5.1"
